"""Stage 1 product visual system for the legal operations workbench."""

APP_CSS = r"""
<style>
:root{--navy:#0b1739;--blue:#315bea;--ink:#14213d;--muted:#68758d;--canvas:#f3f6fb;--panel:#fff;--line:#dfe5ef;--high:#d14343;--high-soft:#fff0f0;--medium:#b86b16;--medium-soft:#fff6e9;--low:#25835b;--low-soft:#eaf8f1}
html,body,[class*="css"]{font-family:Inter,"PingFang SC","Microsoft YaHei",sans-serif}.stApp{background:var(--canvas);color:var(--ink)}#MainMenu,footer,[data-testid="stToolbar"]{visibility:hidden}[data-testid="stHeader"]{background:transparent;height:1rem}.block-container{max-width:1440px;padding:2rem 2.8rem 4rem}

/* Fixed dark application navigation */
[data-testid="stSidebar"]{background:linear-gradient(180deg,var(--navy),#0e1d42);border-right:0;min-width:286px;max-width:286px}[data-testid="stSidebar"]>div:first-child{padding-top:1.2rem}.sidebar-brand{padding:.35rem .4rem 1.25rem;border-bottom:1px solid rgba(255,255,255,.1);margin-bottom:1rem}.sidebar-brand-row{display:flex;align-items:center;gap:.75rem}.sidebar-mark{width:42px;height:42px;display:flex;align-items:center;justify-content:center;border-radius:12px;background:linear-gradient(135deg,#5478ff,#7e9cff);color:#fff;font-weight:850;box-shadow:0 8px 20px rgba(52,91,235,.35)}.sidebar-name{font-size:.94rem;font-weight:780;color:#fff}.sidebar-sub{color:#91a3cb;font-size:.7rem;margin-top:.15rem}.nav-section-label{color:#6579a6;font-size:.62rem;font-weight:750;letter-spacing:.13em;margin:.25rem .6rem .55rem;text-transform:uppercase}
[data-testid="stSidebar"] .stButton{margin:.1rem 0}[data-testid="stSidebar"] .stButton button{justify-content:flex-start;text-align:left;min-height:2.8rem;border-radius:9px;padding-left:1rem;font-size:.86rem;font-weight:620;box-shadow:none}[data-testid="stSidebar"] .stButton button[kind="secondary"]{color:#b9c5df;background:transparent;border:1px solid transparent}[data-testid="stSidebar"] .stButton button[kind="secondary"]:hover{color:#fff;background:rgba(255,255,255,.07);border-color:rgba(255,255,255,.08)}[data-testid="stSidebar"] .stButton button[kind="primary"]{color:#fff;background:linear-gradient(90deg,#315bea,#466ff4);border:0;box-shadow:0 7px 18px rgba(36,74,207,.28)}
.sidebar-footer{margin-top:1.4rem;padding:1rem .55rem;border-top:1px solid rgba(255,255,255,.1);color:#8295bd;font-size:.69rem;line-height:1.65}.sidebar-status{display:flex;align-items:center;gap:.4rem;color:#a9b9d9;font-weight:750;font-size:.63rem;letter-spacing:.08em;margin-bottom:.8rem}.sidebar-status span{width:7px;height:7px;border-radius:50%;background:#52d394;box-shadow:0 0 0 4px rgba(82,211,148,.12)}.sidebar-footer-title{color:#dce5f7;font-weight:700;margin-bottom:.18rem}.sidebar-version{margin-top:.85rem;color:#596f9e;font-size:.6rem;letter-spacing:.08em}

/* Page hierarchy */
.page-head{display:flex;justify-content:space-between;gap:2rem;align-items:flex-start;margin-bottom:1.5rem}.page-head-copy{max-width:820px}.eyebrow{display:flex;align-items:center;gap:.45rem;color:#7483a1;font-size:.65rem;font-weight:800;letter-spacing:.13em;margin-bottom:.55rem}.eyebrow span{width:22px;height:2px;background:var(--blue);display:inline-block}.page-head h1{font-size:2.15rem;line-height:1.1;letter-spacing:-.045em;margin:0;color:#101c35;font-weight:820}.page-subtitle{color:#2b3a59;font-size:1.05rem;font-weight:680;margin-top:.55rem}.page-description{color:var(--muted);font-size:.84rem;margin-top:.42rem;line-height:1.65}.mode-badge{display:inline-flex;align-items:center;gap:.4rem;background:#fff;border:1px solid var(--line);border-radius:999px;padding:.4rem .72rem;color:#53617a;font-size:.66rem;font-weight:750;box-shadow:0 3px 10px rgba(21,37,72,.04)}.mode-dot{width:7px;height:7px;border-radius:50%;background:#50bd8a}

/* Dashboard */
.dashboard-hero{min-height:245px;background:radial-gradient(circle at 90% 20%,rgba(100,133,255,.42),transparent 35%),linear-gradient(135deg,#102650,#183e82);border-radius:18px;padding:2rem 2.15rem;color:#fff;box-shadow:0 18px 40px rgba(20,48,103,.18)}.hero-kicker{font-size:.64rem;font-weight:800;letter-spacing:.15em;color:#91adff}.hero-title{font-size:1.75rem;line-height:1.35;font-weight:800;letter-spacing:-.025em;margin:.6rem 0}.hero-copy{color:#c6d3ee;font-size:.8rem;max-width:620px;line-height:1.7}.hero-flow{display:flex;align-items:center;gap:.58rem;margin-top:1.45rem;flex-wrap:wrap}.hero-flow span{background:rgba(255,255,255,.1);border:1px solid rgba(255,255,255,.13);border-radius:999px;padding:.34rem .65rem;font-size:.67rem}.hero-flow i{font-style:normal;color:#6f91e4}
div[data-testid="stVerticalBlockBorderWrapper"]:has(.quick-card-marker){height:100%;background:#fff;border:1px solid #dbe3f1!important;border-radius:18px!important;box-shadow:0 12px 30px rgba(25,46,88,.08)}div[data-testid="stVerticalBlockBorderWrapper"]:has(.quick-card-marker)>div{padding:1.55rem!important}.quick-kicker{font-size:.64rem;color:var(--blue);font-weight:800;letter-spacing:.13em}.quick-title{font-size:1.22rem;font-weight:790;color:#172440;margin:.7rem 0 .45rem}.quick-copy{color:#718099;font-size:.78rem;line-height:1.6;margin-bottom:1.1rem}
.section-row{display:flex;align-items:baseline;justify-content:space-between;margin:1.8rem 0 .78rem}.section-title{font-size:1.08rem;font-weight:780;color:#1d2a45}.section-note{color:#8a96aa;font-size:.72rem}.demo-tag{display:inline-block;margin-left:.5rem;color:#80601b;background:#fff5d8;border-radius:999px;padding:.13rem .45rem;font-size:.61rem;vertical-align:2px}
.metric-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:1rem}.metric-card{position:relative;overflow:hidden;background:#fff;border:1px solid var(--line);border-radius:14px;padding:1.1rem 1.15rem;box-shadow:0 5px 16px rgba(25,42,77,.045)}.metric-card:before{content:"";position:absolute;left:0;top:0;bottom:0;width:4px;background:#4e75ed}.metric-2:before{background:#e05555}.metric-3:before{background:#8d67d8}.metric-4:before{background:#32a77a}.metric-top{display:flex;justify-content:space-between;align-items:center}.metric-label{font-size:.73rem;color:#748099;font-weight:650}.metric-icon{width:28px;height:28px;display:flex;align-items:center;justify-content:center;border-radius:8px;background:#edf2ff;color:#315bea;font-weight:800}.metric-value{font-size:1.8rem;color:#17223b;font-weight:820;line-height:1.2;margin-top:.45rem}.metric-foot{color:#929caf;font-size:.65rem;margin-top:.28rem}
.panel{background:#fff;border:1px solid var(--line);border-radius:14px;padding:1rem 1.15rem;box-shadow:0 5px 16px rgba(25,42,77,.04)}.dashboard-panels{display:grid;grid-template-columns:minmax(0,1.65fr) minmax(0,1fr);gap:1.25rem}.dashboard-panel-head{display:flex;justify-content:space-between;align-items:center;margin:1.65rem 0 .7rem}.dashboard-panel-head strong{font-size:1rem;color:#1d2a45}.dashboard-panel-head span{font-size:.68rem;color:#8995a8}.clean-table{width:100%;border-collapse:collapse;font-size:.74rem}.clean-table th{text-align:left;color:#8793a7;font-weight:650;padding:.65rem .52rem;border-bottom:1px solid #e8edf4}.clean-table td{color:#45526a;padding:.78rem .52rem;border-bottom:1px solid #edf1f6}.clean-table tr:last-child td{border-bottom:0}.primary-cell{font-weight:680;color:#1d2a45!important}

/* Three-step workflow */
.workflow-steps{display:grid;grid-template-columns:repeat(3,1fr);background:#e7ecf5;border-radius:12px;padding:4px;margin:.4rem 0 1.35rem}.workflow-step{display:flex;align-items:center;justify-content:center;gap:.5rem;padding:.68rem;color:#78859b;font-size:.75rem;border-radius:9px}.workflow-step span{width:22px;height:22px;border-radius:50%;display:flex;align-items:center;justify-content:center;background:#d5dce9;font-size:.65rem}.workflow-step.active{background:#fff;color:#1f3157;box-shadow:0 3px 12px rgba(30,50,91,.08)}.workflow-step.active span{background:var(--blue);color:#fff}.step-head{display:flex;align-items:center;gap:.68rem;margin:1.2rem 0 .68rem}.step-no{width:29px;height:29px;border-radius:9px;background:#142d61;color:#fff;display:flex;align-items:center;justify-content:center;font-size:.72rem;font-weight:800}.step-title{font-size:1.02rem;color:#1c2a46;font-weight:780}
div[data-testid="stVerticalBlockBorderWrapper"]:has(.choice-card-marker){position:relative;background:#fff;border:1px solid #dce4f0!important;border-radius:15px!important;box-shadow:0 4px 14px rgba(24,43,81,.04)}div[data-testid="stVerticalBlockBorderWrapper"]:has(.choice-card-marker.selected){border:2px solid #4169e8!important;background:linear-gradient(180deg,#f7f9ff,#fff);box-shadow:0 8px 24px rgba(49,91,234,.12)}div[data-testid="stVerticalBlockBorderWrapper"]:has(.choice-card-marker)>div{padding:1rem 1.15rem!important}.choice-icon{width:38px;height:38px;border-radius:11px;background:#edf2ff;color:#315bea;display:flex;align-items:center;justify-content:center;font-size:1.15rem;font-weight:800;margin-bottom:.6rem}.choice-title{font-size:1rem;font-weight:780;color:#1b2944}.choice-desc{min-height:38px;color:#748198;font-size:.75rem;line-height:1.55;margin-top:.25rem}.selection-note{border-left:4px solid #4169e8;background:#edf3ff;padding:.65rem .85rem;border-radius:0 9px 9px 0;color:#445c8e;font-size:.74rem;margin:.7rem 0}.confirm-card{background:linear-gradient(135deg,#fff,#f7f9fd);border:1px solid #d9e2f0;border-radius:15px;padding:1.2rem 1.3rem;margin:.7rem 0 1rem;box-shadow:0 6px 18px rgba(25,44,84,.05)}.confirm-title{font-size:.93rem;font-weight:780;color:#1b2944;margin-bottom:.8rem}.confirm-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:.8rem}.confirm-item{background:#fff;border:1px solid #e6ebf2;border-radius:9px;padding:.7rem}.confirm-item span{display:block;color:#8994a7;font-size:.63rem;margin-bottom:.2rem}.confirm-item strong{color:#263754;font-size:.78rem}.output-list{font-size:.72rem;color:#60708a;margin-top:.8rem;padding-top:.7rem;border-top:1px solid #e3e8f0}

/* Executive summary and findings */
.result-hero{background:radial-gradient(circle at 95% 10%,rgba(91,125,255,.4),transparent 33%),linear-gradient(135deg,#10244c,#173c7c);border-radius:18px;padding:1.55rem 1.65rem;margin-bottom:1.15rem;color:#fff;box-shadow:0 16px 36px rgba(20,46,99,.17)}.result-head{display:flex;justify-content:space-between;align-items:flex-start}.result-kicker{color:#9db5ff;font-size:.64rem;font-weight:850;letter-spacing:.15em}.result-title{font-size:1.55rem;font-weight:820;margin-top:.3rem}.result-complete{background:rgba(63,205,147,.13);border:1px solid rgba(92,221,166,.28);color:#86e2bb;border-radius:999px;padding:.36rem .65rem;font-size:.63rem;font-weight:750}.result-summary{color:#c8d4ec;font-size:.8rem;line-height:1.65;margin-top:.55rem;max-width:950px}.result-metrics{display:grid;grid-template-columns:repeat(5,1fr);gap:.65rem;margin-top:1.1rem}.result-metric{background:rgba(255,255,255,.09);border:1px solid rgba(255,255,255,.12);border-radius:10px;padding:.72rem}.result-metric span{display:block;color:#aebddd;font-size:.61rem}.result-metric strong{display:block;color:#fff;font-size:.92rem;margin-top:.25rem}
.finding-card{background:#fff;border:1px solid #dfe5ef;border-left:5px solid #8090aa;border-radius:14px;padding:1.15rem 1.25rem;margin:.85rem 0;box-shadow:0 6px 18px rgba(28,45,78,.045)}.finding-card.high{border-left-color:var(--high)}.finding-card.medium{border-left-color:var(--medium)}.finding-card.low{border-left-color:var(--low)}.finding-top{display:flex;justify-content:space-between;gap:1rem}.finding-index{font-size:.64rem;color:#96a1b2;font-weight:800;letter-spacing:.1em}.finding-title{font-size:1rem;color:#172440;font-weight:760;margin:.17rem 0 .52rem}.finding-grid{display:grid;grid-template-columns:1fr 1fr;gap:.75rem;margin-top:.8rem}.detail-block{background:#f6f8fc;border:1px solid #e8edf5;border-radius:10px;padding:.75rem .82rem}.detail-label{font-size:.62rem;color:#7f8ca2;font-weight:750;margin-bottom:.32rem}.detail-text{font-size:.73rem;color:#48566f;line-height:1.62}.insufficient{background:var(--high-soft);color:#a93434;border-radius:8px;padding:.55rem .7rem;font-size:.7rem;font-weight:700;margin-top:.65rem}

/* Human review workspace */
div[data-testid="stVerticalBlockBorderWrapper"]:has(.review-panel-marker){background:#fff;border:1px solid #dce4ef!important;border-radius:16px!important;box-shadow:0 8px 24px rgba(24,42,78,.055)}div[data-testid="stVerticalBlockBorderWrapper"]:has(.review-panel-marker.ai){border-top:5px solid #4f72e9!important}div[data-testid="stVerticalBlockBorderWrapper"]:has(.review-panel-marker.human){border-top:5px solid #ac7849!important}.review-panel-kicker{font-size:.61rem;font-weight:850;color:#7283a3;letter-spacing:.14em}.column-title{font-size:1.15rem;font-weight:800;color:#182744;margin:.28rem 0 .8rem}.audit-item{position:relative;border-left:2px solid #cbd5e5;padding:.15rem 0 .75rem .9rem;color:#5d6b82;font-size:.72rem}.audit-item:before{content:"";position:absolute;left:-5px;top:.25rem;width:8px;height:8px;border-radius:50%;background:#4169e8}

.badge{display:inline-flex;align-items:center;border-radius:999px;padding:.18rem .52rem;font-size:.62rem;font-weight:760}.badge.high{color:var(--high);background:var(--high-soft)}.badge.medium{color:var(--medium);background:var(--medium-soft)}.badge.low{color:var(--low);background:var(--low-soft)}.badge.neutral{color:#56657d;background:#edf1f6}.badge.review{color:#754b9b;background:#f3eafb}.empty-panel{background:#fff;border:1px dashed #ccd6e5;border-radius:14px;padding:2rem;color:#7b879b;text-align:center}
div.stButton>button,div.stDownloadButton>button{border-radius:9px;min-height:2.5rem;font-weight:690;box-shadow:none}div.stButton>button[kind="primary"],div.stDownloadButton>button[kind="primary"]{background:linear-gradient(90deg,#315bea,#456cf0);border:0;color:#fff;box-shadow:0 7px 16px rgba(49,91,234,.2)}div.stButton>button[kind="primary"]:hover{background:#244bd5}[data-testid="stFileUploader"]{background:#fff;border:2px dashed #cbd6e7;border-radius:13px;padding:.7rem}[data-testid="stTextArea"] textarea,[data-testid="stSelectbox"]>div>div{border-radius:9px}[data-testid="stExpander"]{background:#fff;border:1px solid var(--line);border-radius:10px}[data-testid="stAlert"]{border-radius:9px}
@media(max-width:1050px){.metric-grid{grid-template-columns:repeat(2,1fr)}.dashboard-panels{grid-template-columns:1fr}.result-metrics{grid-template-columns:repeat(3,1fr)}.block-container{padding:1.5rem}}@media(max-width:720px){[data-testid="stSidebar"]{min-width:auto}.page-head{flex-direction:column}.metric-grid,.confirm-grid,.result-metrics,.finding-grid,.workflow-steps{grid-template-columns:1fr}.block-container{padding:1rem}}
/* Stage 2 — Xiezhi delivers the scroll, Gaotao reviews the covenant */
.sidebar-mark svg{width:31px;height:31px}.sidebar-mark svg path{fill:none;stroke:#fff;stroke-width:2.1;stroke-linecap:round;stroke-linejoin:round}
.block-container:has(.process-page-marker){max-width:1360px;padding-top:1.35rem;background:linear-gradient(180deg,#f6f2e9 0,#f3f6fb 78%)}
.review-process{--cinnabar:#8f2f2b;--bronze:#536b63;color:#252823}.process-heading{text-align:center;padding:.35rem 0 1.1rem}.process-kicker{font-size:.63rem;letter-spacing:.2em;font-weight:800;color:#8a7569}.process-heading h1{font-family:"Songti SC","STSong","Noto Serif SC",serif;font-size:2.15rem;letter-spacing:.08em;font-weight:650;color:#252824;margin:.38rem 0}.process-heading h1 i{font-style:normal;color:var(--cinnabar);font-size:1rem;vertical-align:.35rem}.process-heading p{color:#79776f;font-size:.8rem;margin:0}
.process-scene{position:relative;overflow:hidden;background:radial-gradient(circle at 50% 115%,rgba(129,105,69,.12),transparent 45%),linear-gradient(150deg,#fffdf8,#f2ecdf);border:1px solid #ddd3c2;border-radius:20px;box-shadow:0 18px 46px rgba(68,54,34,.08);min-height:370px}.process-scene:before{content:"审契";position:absolute;right:26px;top:22px;border:1px solid rgba(143,47,43,.34);color:rgba(143,47,43,.4);font-family:"Songti SC",serif;font-size:.7rem;letter-spacing:.2em;padding:.45rem .32rem .38rem .5rem}.process-scene svg{display:block;width:100%;height:auto;max-height:410px}.horizon,.screen-lines path{fill:none;stroke:#b9ad99;stroke-width:1}.screen-lines{opacity:.35}.xiezhi-mark path,.xiezhi-mark circle{fill:none;stroke:#35423f;stroke-width:4;stroke-linecap:round;stroke-linejoin:round}.xiezhi-mark .horn{stroke:var(--cinnabar);stroke-width:5}.xiezhi-mark{opacity:.28;transform-origin:210px 220px;transition:opacity .5s ease,transform .5s ease}.delivery-path{fill:none;stroke:#9b796a;stroke-width:2;stroke-dasharray:5 9;opacity:.35}.scroll{transform:translate(335px,260px);transition:transform .7s cubic-bezier(.22,.8,.3,1),opacity .35s ease}.scroll rect{stroke:#b5a790;stroke-width:2}.scroll path,.scroll-rod{fill:none;stroke:#887969;stroke-width:2}.scroll-seal{fill:#9a3732;opacity:.72}.law-pages{opacity:0;transition:opacity .45s ease}.law-pages rect{fill:#fbf7ed;stroke:#a99c86;stroke-width:2}.law-pages path{fill:none;stroke:#988b76;stroke-width:2}.gaotao-mark{opacity:.26;transition:opacity .5s ease}.gaotao-mark circle,.gaotao-mark path{fill:none;stroke:#3c403d;stroke-width:4;stroke-linecap:round;stroke-linejoin:round}.gaotao-mark .pen{stroke:#8f2f2b;stroke-width:3}
.stage-received .xiezhi-mark{opacity:1;animation:xiezhi-arrive .55s ease both}.stage-received .scroll{transform:translate(292px,264px)}.stage-parsing .xiezhi-mark,.stage-planning .xiezhi-mark,.stage-retrieving .xiezhi-mark,.stage-analyzing .xiezhi-mark,.stage-validating .xiezhi-mark,.stage-reporting .xiezhi-mark,.stage-completed .xiezhi-mark{opacity:.76}.stage-parsing .scroll{transform:translate(515px,255px);animation:scroll-deliver .7s ease both}.stage-planning .scroll,.stage-retrieving .scroll,.stage-analyzing .scroll,.stage-validating .scroll,.stage-reporting .scroll,.stage-completed .scroll{transform:translate(760px,264px) scale(1.08)}.stage-planning .gaotao-mark,.stage-retrieving .gaotao-mark,.stage-analyzing .gaotao-mark,.stage-validating .gaotao-mark,.stage-reporting .gaotao-mark,.stage-completed .gaotao-mark{opacity:1}.stage-retrieving .law-pages,.stage-analyzing .law-pages,.stage-validating .law-pages,.stage-reporting .law-pages,.stage-completed .law-pages{opacity:1}.stage-analyzing .pen{animation:pen-review .48s ease-in-out infinite alternate}.stage-analyzing .scroll-seal,.stage-validating .scroll-seal{animation:risk-mark .65s ease-in-out infinite alternate}.stage-reporting .scroll,.stage-completed .scroll{transform:translate(785px,268px) scale(.92)}.stage-completed .scroll-seal{opacity:1;transform:scale(1.18);transform-origin:52px 18px}.stage-failed .process-scene{filter:grayscale(.55);opacity:.7}
.desk path{fill:#5c5145;opacity:.9}.risk-marks{opacity:0}.risk-marks path,.risk-marks circle{fill:none;stroke:#a23a34;stroke-width:3}.completion-seal{opacity:0}.completion-seal circle,.completion-seal path{fill:none;stroke:#9a3732;stroke-width:4}.stage-analyzing .risk-marks,.stage-validating .risk-marks,.stage-reporting .risk-marks{opacity:1}.stage-completed .completion-seal{opacity:.82;animation:seal-arrive .5s ease both}.scene-label{position:absolute;bottom:18px;color:#4c4c45}.scene-label strong{display:block;font-family:"Songti SC",serif;font-size:1rem}.scene-label span{font-size:.62rem;color:#8b857a}.xiezhi-label{left:9%}.gaotao-label{right:10%}
.process-status{display:flex;align-items:center;gap:.8rem;padding:.85rem .25rem .35rem}.status-mark{width:36px;height:36px;border:1px solid rgba(143,47,43,.35);border-radius:50%;display:flex;align-items:center;justify-content:center}.status-mark span{width:8px;height:8px;background:#8f2f2b;border-radius:50%}.process-stage-title{font-family:"Songti SC",serif;font-size:1.12rem;color:#30312d;font-weight:700}.process-stage-copy{display:block!important;font-size:.72rem;color:#827d74;margin-top:.16rem}.process-file{margin-left:auto;text-align:right;color:#91897c;font-size:.61rem;max-width:34%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.process-file strong{color:#534f48;font-size:.68rem}.process-progress{display:grid;grid-template-columns:repeat(6,1fr);gap:.45rem;margin:.75rem 0}.process-footnote{text-align:center;color:#aaa195;font-size:.61rem}.stage-failed .status-mark span{background:#9e3f3a}
.process-stage-copy{display:none}.process-steps{display:grid;grid-template-columns:repeat(6,1fr);gap:.45rem;margin:1rem 0 .75rem}.process-step{position:relative;text-align:center;color:#aaa69c;font-size:.69rem;padding:.65rem .2rem;border-top:2px solid #ded7ca}.process-step span{display:block;font-size:.72rem;margin-bottom:.22rem}.process-step.done{color:#526a61;border-color:#718b81}.process-step.active{color:#762b28;border-color:#9b3934;background:rgba(143,47,43,.045);border-radius:0 0 8px 8px}.process-step.active span{animation:stage-pulse .85s ease-in-out infinite alternate}.process-step strong{font-weight:680}.process-current{display:flex;align-items:center;gap:.75rem;max-width:700px;margin:.9rem auto 0;background:#fff;border:1px solid #e1dbd0;border-radius:12px;padding:.72rem .9rem;box-shadow:0 5px 16px rgba(54,46,35,.04)}.process-current>span{width:9px;height:9px;border-radius:50%;background:#8f2f2b;box-shadow:0 0 0 5px rgba(143,47,43,.1)}.process-current small,.process-current strong{display:block}.process-current small{font-size:.6rem;color:#9a948a;letter-spacing:.08em}.process-current strong{font-size:.75rem;color:#46453f;margin-top:.1rem}.manual-review-notice{border-left:5px solid #9b3934;background:#fff7f5;border-radius:10px;padding:.85rem 1rem;margin:0 0 1rem}.manual-review-notice span{display:block;color:#9b3934;font-size:.59rem;letter-spacing:.12em;font-weight:800}.manual-review-notice strong{display:block;color:#632925;font-size:1rem;margin:.2rem 0}.manual-review-notice p{color:#786864;font-size:.73rem;margin:0}
@keyframes xiezhi-arrive{from{opacity:.08;transform:translateX(-12px)}to{opacity:1;transform:none}}@keyframes scroll-deliver{from{opacity:.45;transform:translate(305px,255px)}to{opacity:1;transform:translate(515px,255px)}}@keyframes pen-review{from{transform:translate(-3px,3px)}to{transform:translate(4px,-3px)}}@keyframes risk-mark{from{opacity:.45}to{opacity:1}}@keyframes stage-pulse{from{opacity:.45}to{opacity:1}}
@media(prefers-reduced-motion:reduce){.review-process *{animation:none!important;transition:none!important}.process-step.active span{opacity:1}}
@keyframes seal-arrive{from{opacity:0;transform:scale(1.35)}to{opacity:.82;transform:scale(1)}}
@media(max-width:900px){.process-scene{min-height:auto}.process-steps,.process-progress{grid-template-columns:repeat(3,1fr)}.process-heading h1{font-size:1.65rem}.process-file{display:none}}
</style>
"""
